source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use mysql as the database for Active Record
gem 'mysql2'
gem 'devise'
gem 'opro'
gem 'jquery-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'mocha'
  gem 'factory_girl_rails'
end